CREATE TABLE plicometrie (
    id UUID PRIMARY KEY,
    visita_id UUID NOT NULL UNIQUE REFERENCES visite(id),
    protocollo VARCHAR(30) NOT NULL,
    formula_versione VARCHAR(40) NOT NULL,
    eta_anni INTEGER NOT NULL,
    coefficiente_c NUMERIC(6,4),
    coefficiente_m NUMERIC(6,4),
    etnia_atleta VARCHAR(20),
    plica_pettorale_mm NUMERIC(5,2),
    plica_ascellare_mm NUMERIC(5,2),
    plica_tricipitale_mm NUMERIC(5,2),
    plica_bicipitale_mm NUMERIC(5,2),
    plica_sottoscapolare_mm NUMERIC(5,2),
    plica_soprailiaca_mm NUMERIC(5,2),
    plica_addominale_mm NUMERIC(5,2),
    plica_coscia_mm NUMERIC(5,2),
    plica_polpaccio_mm NUMERIC(5,2),
    somma_pliche_mm NUMERIC(6,2) NOT NULL,
    densita_corporea NUMERIC(6,4),
    percentuale_grasso NUMERIC(5,2) NOT NULL,
    massa_grassa_kg NUMERIC(6,2) NOT NULL,
    massa_magra_kg NUMERIC(6,2) NOT NULL,
    fmi NUMERIC(5,2) NOT NULL,
    ffmi NUMERIC(5,2) NOT NULL,
    creato_il TIMESTAMPTZ NOT NULL DEFAULT now()
);
